
GAP_WARNING_THRESHOLD_CHARS = 2000
SUBSTANTIVE_GAP_THRESHOLD_CHARS = 500
ANCHOR_SEARCH_BUFFER_BEFORE = 5000
ANCHOR_SEARCH_EXTENDED_WINDOW = 50000
TABLE_TRUNCATION_THRESHOLD_RATIO = 0.80
EXTRACTION_COMPLETE_THRESHOLD_PCT = 95.0
DUPLICATE_WARNING_THRESHOLD_RATIO = 1.5
SECTION_INTRO_MIN_LENGTH_CHARS = 100
ESTIMATED_TOKENS_PER_SECTION_METADATA = 100
TOKENS_PER_SECTION_ESTIMATE = 2000
